import { env } from "cloudflare:workers";
import { currentUser, isAdmin } from "../../../../lib/user-auth";
export const dynamic = "force-dynamic";
export async function GET(request: Request) {
  const user=await currentUser(request); if(!user||!isAdmin(user))return Response.json({error:"Administrator access required."},{status:403});
  const db=(env as unknown as {DB:D1Database}).DB; const day=86_400_000; const now=Date.now(); const since7=now-7*day; const since30=now-30*day;
  const q=async(sql:string,...args:unknown[])=>db.prepare(sql).bind(...args).first<Record<string,number|string>>();
  const [users,dau,wau,mau,events7,views7,saves7,shares7,sources7,refresh7,returning,depth,topics,recent]=await Promise.all([
    q("SELECT COUNT(*) value FROM users WHERE deleted_at IS NULL"),q("SELECT COUNT(DISTINCT COALESCE(user_id,anonymous_id)) value FROM user_events WHERE occurred_at>=?",now-day),q("SELECT COUNT(DISTINCT COALESCE(user_id,anonymous_id)) value FROM user_events WHERE occurred_at>=?",since7),q("SELECT COUNT(DISTINCT COALESCE(user_id,anonymous_id)) value FROM user_events WHERE occurred_at>=?",since30),q("SELECT COUNT(*) value FROM user_events WHERE occurred_at>=?",since7),q("SELECT COUNT(*) value FROM user_events WHERE event_name='story_viewed' AND occurred_at>=?",since7),q("SELECT COUNT(*) value FROM user_events WHERE event_name='story_saved' AND occurred_at>=?",since7),q("SELECT COUNT(*) value FROM user_events WHERE event_name IN ('share_completed','share_downloaded') AND occurred_at>=?",since7),q("SELECT COUNT(*) value FROM user_events WHERE event_name='source_opened' AND occurred_at>=?",since7),q("SELECT COUNT(*) value FROM user_events WHERE event_name='feed_refreshed' AND occurred_at>=?",since7),q("SELECT COUNT(*) value FROM (SELECT COALESCE(user_id,anonymous_id) person FROM user_events WHERE occurred_at>=? GROUP BY person HAVING COUNT(DISTINCT date(occurred_at/1000,'unixepoch'))>=2)",since7),q("SELECT ROUND(AVG(c),1) value FROM (SELECT session_id,COUNT(*) c FROM user_events WHERE occurred_at>=? GROUP BY session_id)",since7),db.prepare("SELECT topic,COUNT(*) value FROM user_events WHERE topic IS NOT NULL AND topic<>'' AND occurred_at>=? GROUP BY topic ORDER BY value DESC LIMIT 8").bind(since7).all(),db.prepare("SELECT event_name,story_id,topic,occurred_at FROM user_events ORDER BY occurred_at DESC LIMIT 50").all()
  ]);
  return Response.json({kpis:{users:users?.value||0,dau:dau?.value||0,wau:wau?.value||0,mau:mau?.value||0,events7:events7?.value||0,views7:views7?.value||0,saves7:saves7?.value||0,shares7:shares7?.value||0,sources7:sources7?.value||0,refresh7:refresh7?.value||0,returning7:returning?.value||0,sessionDepth:depth?.value||0},topics:topics.results,recent:recent.results});
}
