import { LegalLayout } from "../legal-layout";

export default function Privacy() {
  return <LegalLayout kicker="LEGAL" title="Privacy policy">
    <p className="legal-callout">IntelFlow is a general-audience news discovery app for people aged 13 and over. It is not designed for young children.</p>
    <h2>Who operates IntelFlow</h2><p>IntelFlow is a product of Swarnim Capital, a sole proprietorship operating from 537, Florence Excellence, Vasna Bhayli, Vadodara, Gujarat 391410, India. Privacy enquiries may be sent to <a href="mailto:hello@swarnimcapital.com">hello@swarnimcapital.com</a>.</p>
    <h2>Information stored on your device</h2><p>The guest experience stores selected interests, bookmarks and onboarding status in browser or application storage. Clearing that storage resets these preferences.</p>
    <h2>Accounts and sharing profiles</h2><p>When Google sign-in is enabled, IntelFlow will receive the Google account name, email address, profile image and Google account identifier needed to create and secure an account. Users may edit their display name, title and profile image. These details are used only to personalise the app and to place the user’s chosen identity on a story image they create. Do not add sensitive personal information.</p>
    <h2>Technical information</h2><p>Cloudflare may process ordinary request information such as IP address, device/browser information, timestamps and requested pages for security, reliability and abuse prevention. We minimise access to legitimate operational purposes.</p>
    <h2>Analytics</h2><p>IntelFlow uses Google Analytics 4, measurement ID G-9JP9G1RWRY, to understand matters such as page visits, approximate location, device and browser category, referral source and interaction patterns. Google may process identifiers and technical information under its own privacy terms. Analytics is used to measure product performance and improve the briefing experience; it is not used by IntelFlow to make investment recommendations.</p>
    <h2>Product activity</h2><p>IntelFlow records product events such as sessions, story opens, saves, source opens, topic selections, refreshes and share-image actions. Signed-in events may be associated with the user account; guest events use random browser and session identifiers. This supports feed quality, product reliability, audience measurement and abuse prevention. We do not collect message contents or learn who receives a shared image.</p>
    <h2>Data retention and deletion</h2><p>Guest preferences remain on the device until the user clears application/browser data. Account users will be able to request account deletion through the support address. We retain only information reasonably needed for security, fraud prevention, legal compliance and resolving disputes.</p>
    <h2>Your choices</h2><p>You may clear local application data and analytics cookies through your browser settings, use browser tracking protections or install Google’s Analytics opt-out tool where supported. Requests concerning personal data, correction, access or deletion may be sent to the support address above. Identity verification may be required before completing a request.</p>
    <h2>Security and changes</h2><p>Reasonable safeguards will be used, but no internet service can promise absolute security. Material changes will be reflected through a revised effective date and, where appropriate, an in-product notice or consent request.</p>
  </LegalLayout>;
}
