import { LegalLayout } from "../legal-layout";

export default function Privacy() {
  return <LegalLayout kicker="LEGAL" title="Privacy policy">
    <p className="legal-callout">IntelFlow uses limited website analytics to understand aggregate usage and improve the product. Advertising and account services are not active in this build.</p>
    <h2>Who operates IntelFlow</h2><p>IntelFlow is a product of Swarnim Capital, a sole proprietorship operating from 537, Florence Excellence, Vasna Bhayli, Vadodara, Gujarat 391410, India. Privacy enquiries may be sent to <a href="mailto:hello@swarnimcapital.com">hello@swarnimcapital.com</a>.</p>
    <h2>Information stored on your device</h2><p>The guest experience stores selected interests, bookmarks, onboarding status, distributor-profile preferences and private share-link owner keys in browser or application storage on your device. Clearing that storage may remove your ability to view activity for or revoke links created from that device.</p>
    <h2>Branded share links</h2><p>When you choose to create a branded share link, IntelFlow stores the displayed distributor name, ARN, EUIN, business phone, disclaimer, brand colour, story context, source link, preview image, expiry date and aggregate activity counts. These details become visible to anyone who receives the link until it expires or is revoked. Do not enter or publish client information. IntelFlow counts page views, source opens and “Discuss this with me” clicks without creating a visitor profile or storing message contents.</p>
    <h2>Technical information</h2><p>Cloudflare may process ordinary request information such as IP address, device/browser information, timestamps and requested pages for security, reliability and abuse prevention. We minimise access to legitimate operational purposes.</p>
    <h2>Analytics</h2><p>IntelFlow uses Google Analytics 4, measurement ID G-9JP9G1RWRY, to understand matters such as page visits, approximate location, device and browser category, referral source and interaction patterns. Google may process identifiers and technical information under its own privacy terms. Analytics is used to measure product performance and improve the briefing experience; it is not used by IntelFlow to make investment recommendations.</p>
    <h2>Accounts and advertising</h2><p>Accounts and advertising are not active. Before either is enabled, IntelFlow will update this policy to describe the providers, data processed, purposes, retention and available choices. Any Google Play Data Safety declaration will be aligned with actual application behaviour.</p>
    <h2>Data retention and deletion</h2><p>Guest preferences and private share-link owner keys remain on the device until the user clears application/browser data. Published links remain available until their selected expiry date or until the creator revokes them from the originating browser. Revocation removes public access and the stored preview image; limited metadata may be retained for security, dispute handling and operational integrity. If accounts are introduced, IntelFlow will explain account deletion and any additional retention.</p>
    <h2>Your choices</h2><p>You may clear local application data and analytics cookies through your browser settings, use browser tracking protections or install Google’s Analytics opt-out tool where supported. Requests concerning personal data, correction, access or deletion may be sent to the support address above. Identity verification may be required before completing a request.</p>
    <h2>Security and changes</h2><p>Reasonable safeguards will be used, but no internet service can promise absolute security. Material changes will be reflected through a revised effective date and, where appropriate, an in-product notice or consent request.</p>
  </LegalLayout>;
}
