import { LegalLayout } from "../legal-layout";

export default function Terms() {
  return <LegalLayout kicker="LEGAL" title="Terms of use">
    <p className="legal-callout">IntelFlow is an automated news discovery and summarisation product. It is not a newspaper, investment adviser, medical provider or legal adviser.</p>
    <h2>Service</h2><p>IntelFlow organises links and short automated briefs from third-party publishers and can create expiring, co-branded context pages that direct readers to the original source. IntelFlow does not reproduce the full publisher article. Availability, sources and features may change. The original publisher remains responsible for its reporting, and users should consult the original article before relying on important information.</p>
    <h2>Acceptable use</h2><p>You may use IntelFlow for lawful, personal information discovery. You must not interfere with the service, attempt unauthorised access, automate abusive requests, evade technical restrictions, misrepresent affiliation, or use the service to violate another party’s rights.</p>
    <h2>No professional advice</h2><p>Financial and market coverage is general news, not a recommendation, research report, solicitation or personalised investment advice. Health, legal and other specialist coverage is informational only. Seek an appropriately qualified professional before acting.</p>
    <h2>Distributor communications</h2><p>Users who publish branded links are responsible for reviewing accuracy, keeping their registration details and disclaimers current, following their organisation’s approval process and complying with applicable advertising, distribution and professional rules. A template, disclaimer or activity count does not mean that IntelFlow has approved a communication or certified regulatory compliance. Users must not include client personal information in a share page.</p>
    <h2>Third-party content and links</h2><p>Headlines, images, excerpts and links may originate from third parties. Their own terms and privacy practices apply when you visit them. Inclusion does not imply endorsement. IntelFlow may remove, correct, suppress or relabel material when a source, rights-holder or user raises a credible concern.</p>
    <h2>Automated summaries</h2><p>Briefs may omit context or contain errors due to source changes or automated processing. IntelFlow does not guarantee completeness, accuracy, neutrality, timeliness or uninterrupted availability. Important claims should be checked against the linked publication and other reliable sources.</p>
    <h2>Liability</h2><p>To the maximum extent permitted by applicable law, the service is provided on an “as available” basis without implied warranties. Swarnim Capital will not be responsible for indirect or consequential losses arising solely from reliance on automated briefs or third-party material. Nothing in these terms excludes liability that cannot lawfully be excluded.</p>
    <h2>Governing law</h2><p>These terms are governed by the laws of India. Subject to applicable consumer law and mandatory dispute forums, courts with jurisdiction in Vadodara, Gujarat will have jurisdiction.</p>
  </LegalLayout>;
}
